#pragma once

#define USERSPACE_VIRT_START 0x0
#define USERSPACE_VIRT_END 0xbfffffff

#define KERNEL_VIRT_START 0xc0000000
#define KERNEL_VIRT_END 0xc03fffff

#define HEAP_VIRT_START 0xc0400000
#define HEAP_VIRT_END 0xff3ffff

#define FRAMEBUFFER_VIRT_START 0xff400000
#define FRAMEBUFFER_VIRT_END 0xffbfffff

#define PAGE_DIR_VIRT 0xffc00000
#define PAGE_DIR_TABLE_VIRT 0xfffff000

#define FRAMEBUFFER_PHYS_START 0xfd000000

#define PHYS_TO_VIRT(p) (p + KERNEL_VIRT_START)
#define VIRT_TO_PHYS(p) (p - KERNEL_VIRT_START)
